version: "2"

services:

  znc:
    image: larsks/znc:e35e23c9
    command: -nf
    ports:
      - "6667:6667"
      - "6697:6697"
      - "443:8443"
    environment:
      ZNCDIR: /znc
    volumes:
      - "./znc:/znc"
      - "./znc-log:/znc/moddata/log"

  bitlbee:
    image: larsks/bitlbee:51306c27
    volumes:
      - "./bitlbee:/var/lib/bitlbee"
      - "./bitlbee.conf:/etc/bitlbee/bitlbee.conf"
    environment:
      BITLBEE_DAEMONPORT: 7667
    network_mode: "service:znc"
